### ISSUE TITLE
Allow species to have negative prices and ensure that the fleet responds accordingly

### ISSUE THREAD

**Issue by DanOvando** [DanOvando/marlin#32]
Right now fleets distribute themselves according to total revenue (across all species) in a patch. 

I think adding in negative prices for a species should do more or less the right thing already, as it would bring revenue down for that patch. But, I think it would break things if revenue actually goes below 0. 

So, see if you can make sure that a) negative prices actually work and b) make sure that the fleet model still works even if revenues are negative (e.g. make revenues  that the fleet responds to always greater than or equal to zero, such that if there are negative revenues the fleet just doesn't go there)

This starts  here

https://github.com/DanOvando/marlin/blob/771e449ec5cf9ddc2e8a1a8b29bf89964015c6f6/R/simmar.R#L105

and 

here

https://github.com/DanOvando/marlin/blob/771e449ec5cf9ddc2e8a1a8b29bf89964015c6f6/R/simmar.R#L111

Once you get it working, create either another vignette or a section to the readme showing what happens when prices are negative for a species

**Comment by echelleburns** [comment]
Made a branch called `negative-prices` to test this. 

Edited this line to limit the values to 0 or greater for fleet responses. 

https://github.com/DanOvando/marlin/blob/negative-prices/R/simmar.R#L111

Tried testing how the model responded if the costs associated with catching Shortfin Mako were negative, and ran into some weird results (probably something I did wrong in the simmar.R)

See: https://github.com/DanOvando/marlin/blob/negative-prices/vignettes/marlin.Rmd#L525:L658

It seems like when Yellowfin Tuna prices = 10, once Shortfin Mako prices < -28, things start to go wonky. It's easier to see the wonkiness if you change the years to = 100. Eventually, both species decline to 0% unfished.

**Comment by DanOvando** [comment]
Hmmm weird. Try moving the `pmax`  around just the revenues, not the effort (but that shouldn't cause that). Also see what happens if you change tune_type to "explt" instead of "depletion": I'm guessing depletion will fail when prices are negative 

https://github.com/DanOvando/marlin/blob/90fbfc182d1447f657f41f54504faf39d09bb42c/vignettes/marlin.Rmd#L58

**Comment by echelleburns** [comment]
Cool. I pushed an update to the `negative-prices` branch

https://github.com/DanOvando/marlin/blob/negative-prices/R/simmar.R#L111 now reads: 
`sum(fleets[[l]]$e_p_s[, s - 1]) * pmax(rowSums(r_p_f), 0) / pmax(sum(rowSums(r_p_f)), 1e-6)`

I also changed `tune_type <- "explt"` and it seemed to do the trick.

I added two examples at the end of the `marlin.Rmd` vingette in this branch. One for where the habitat distributions overlap and one for when they do not. Check to make sure that these results make sense? Each time, both populations increase to 100% of unfished biomass within 100 years. I'm guessing it's because of the dispersion parameter, that eventually after `x` amount of time the habitats begin to overlap again?
